package com.raynaldgitaz.resturantt.navigation

const val ROUTE_SIGNUP = "signup"
const val ROUTE_LOGIN = "login"
const val ROUTE_HOME = "home"
const val ROUTE_INTERIOR_HOMESCREEN = "interior_homescreen"
const val ROUTE_ADD_FOOD = "add_food"
const val SPLASH = "splash"
const val ROUTE_VIEW_FOOD = "view_food"
const val ROUTE_UPDATE_FOOD = "update_food"
const val ROUTE_VIEW_UPLOADS = "view_uploads"
const val ROUTE_ABOUT = "about"
const val ROUTE_VIEW_UPLOAD_DRINKS = "upload_drinks"
const val ROUTE_UPDATE_DRINKS = "update_drinks"
const val ROUTE_VIEW_DRINKS = "view_drinks"
const val ROUTE_ADD_DRINKS = "add_drinks"
